apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "lab"
  type:  "service"
  lifecycle: "experimental"
  owner: "dev-team"
metadata:
  name: "teste-kiali"
  description: "Teste do Kiali"
  annotations:
    github.com/project-slug: analect-io/teste-kiali
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: dev-teste-kiali
    backstage.io/kubernetes-id: "teste-kiali"
    sonarqube.org/project-key: "teste-kiali"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="teste-kiali"}
    prometheus.io/alert: all
  tags:
    - golang
    - "lab"
    - "service"
    - "experimental"
  links:
    - url: https://teste-kiali.analect.com
      title: Website
      icon: Website
    - url: https://grafana.analect.com/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.analect.com/
      title: Alerts
      icon: alert
    - url: https://argocd.analect.com/applications/dev-teste-kiali?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.analect.com/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=teste-kiali&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.analect.com/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=teste-kiali&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
